<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(PortableTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/app/GitUI.Avalonia/GitUI.Avalonia.csproj" />
  </ItemGroup>
</Project>
