// GitExtensionsShellEx.idl : IDL source for GitExtensionsShellEx.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (GitExtensionsShellEx.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(b1a1376c-c4a4-58cb-a3a9-fdc18aaab70f),
		dual,
		helpstring("IGitExtensionsShellEx Interface"),
		pointer_default(unique)
	]
	interface IGitExtensionsShellEx : IDispatch
	{
	};

[
	uuid(c6acb2ce-f155-5779-b93e-f09bdb5f5c3d),
	version(1.0),
	helpstring("GitExtensionsShellEx 1.0 Type Library")
]
library GITEXTENSIONSSHELLEXLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(c058a8b1-7307-5439-a0e8-676b85d54f6f),
		helpstring("GitExtensionsShellEx Class")
	]
	coclass GitExtensionsShellEx
	{
		[default] interface IGitExtensionsShellEx;
	};
};
